<a href="https://colab.research.google.com/github/ErikaDenisse29/ColabFiles/blob/main/calculoMatriz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# Definir la matriz B
B = np.array([[9, -2, 2],
              [-2, 10, 2],
              [2, 2, 6]])

# Paso 1: Calcular el determinante de B
det_B = np.linalg.det(B)
print(f"Determinante de B: {det_B}")

# Paso 2: Calcular la matriz de cofactores
def cofactor_matrix(matrix):
    cofactors = np.zeros(matrix.shape)
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            # Obtener la submatriz al eliminar la fila i y la columna j
            submatrix = np.delete(np.delete(matrix, i, axis=0), j, axis=1)
            # Calcular el determinante de la submatriz
            cofactors[i, j] = ((-1) ** (i + j)) * np.linalg.det(submatrix)
    return cofactors

# Calcular la matriz de cofactores
C = cofactor_matrix(B)
print("Matriz de cofactores:")
print(C)

# Paso 3: Calcular la matriz adjunta (transpuesta de la matriz de cofactores)
adj_B = C.T
print("Matriz adjunta de B:")
print(adj_B)

# Paso 4: Calcular la matriz inversa de B
if det_B != 0:
    B_inv = (1 / det_B) * adj_B
    print("La matriz inversa de B es:")
    print(B_inv)
else:
    print("La matriz B no es invertible (determinante es cero).")

Determinante de B: 423.9999999999996
Matriz de cofactores:
[[ 56.  16. -24.]
 [ 16.  50. -22.]
 [-24. -22.  86.]]
Matriz adjunta de B:
[[ 56.  16. -24.]
 [ 16.  50. -22.]
 [-24. -22.  86.]]
La matriz inversa de B es:
[[ 0.13207547  0.03773585 -0.05660377]
 [ 0.03773585  0.11792453 -0.05188679]
 [-0.05660377 -0.05188679  0.20283019]]
