<a href="https://colab.research.google.com/github/ErikaDenisse29/ColabFiles/blob/main/Practica4_256027.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Manipulación de matrices.**

Crea dos matrices de 3x3 con números aleatorios entre 1 y 10. Realiza las siguientes operaciones:


*   Suma ambas matrices.
*   Resta la segunda matriz de la primera.
*   Multiplica la primera matriz por 2.
*   Realiza una multiplicación matricial entre las dos matrices.









In [6]:
#Importar la biblioteca con un alias
import numpy as np

# Crear un arreglo de 3x3 con números enteros aleatorios entre 1 y 10
array_3x3 = np.random.randint(1, 10, size=(3, 3))

# Mostrar el arreglo
print("Primer Arreglo 3x3:\n", array_3x3)

# Crear otro arreglo de 3x3 para realizar operaciones
array_3x3_2 = np.random.randint(1, 11, size=(3, 3))

# Mostrar el segundo arreglo
print("\nSegundo Arreglo 3x3:\n", array_3x3_2)

# Suma
suma = array_3x3 + array_3x3_2
print("\nSuma:\n", suma)

# Resta
resta = array_3x3_2 - array_3x3
print("\nResta:\n", resta)

# Multiplicación * 2
multiplicacion = array_3x3 * 2
print("\nMultiplicación:\n", multiplicacion)

# Multiplicación matricial
multiplicacion = array_3x3 * array_3x3_2
print("\nMultiplicación:\n", multiplicacion)



Primer Arreglo 3x3:
 [[6 3 4]
 [5 9 1]
 [6 3 9]]

Segundo Arreglo 3x3:
 [[ 1  1  1]
 [10  9 10]
 [ 3  8  7]]

Suma:
 [[ 7  4  5]
 [15 18 11]
 [ 9 11 16]]

Resta:
 [[-5 -2 -3]
 [ 5  0  9]
 [-3  5 -2]]

Multiplicación:
 [[12  6  8]
 [10 18  2]
 [12  6 18]]

Multiplicación:
 [[ 6  3  4]
 [50 81 10]
 [18 24 63]]
